import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Cativo Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap"></link>
      </head>
      <body className={`font-poppins`}>{children}</body>
    </html>
  )
}
